export interface CloserCard {
  category: string;
  prompt: string;
}

// Original prompts written for Pop — not affiliated with or copied from any
// commercial card game.
export const CLOSER_DECK: CloserCard[] = [
  // Warm-up — light, easy openers
  { category: "Warm-up", prompt: "What's a small thing that made you smile this week?" },
  { category: "Warm-up", prompt: "What's a song that instantly puts you in a good mood?" },
  { category: "Warm-up", prompt: "What's something you're looking forward to right now?" },
  { category: "Warm-up", prompt: "What's a food you could eat every day and not get sick of?" },
  { category: "Warm-up", prompt: "What's your favorite memory from the last month?" },
  { category: "Warm-up", prompt: "What's a smell that instantly takes you somewhere else?" },
  { category: "Warm-up", prompt: "What's the best thing that happened to you today?" },
  { category: "Warm-up", prompt: "What's a movie or show you could rewatch forever?" },
  { category: "Warm-up", prompt: "What's something small that always makes your day better?" },
  { category: "Warm-up", prompt: "If we could teleport anywhere right now, where would you pick?" },
  { category: "Warm-up", prompt: "What's a weirdly specific thing you're really good at?" },
  { category: "Warm-up", prompt: "What's your go-to comfort activity after a rough day?" },
  { category: "Warm-up", prompt: "What's a habit of mine that secretly makes you laugh?" },
  { category: "Warm-up", prompt: "What's something you've never told anyone because it's too silly?" },
  { category: "Warm-up", prompt: "What's a place that feels like 'us'?" },
  { category: "Warm-up", prompt: "What's a small tradition you never want to lose?" },
  { category: "Warm-up", prompt: "What's the last thing that made you laugh out loud?" },
  { category: "Warm-up", prompt: "What's a simple pleasure you never get tired of?" },
  { category: "Warm-up", prompt: "What's something you're weirdly nostalgic for already?" },
  { category: "Warm-up", prompt: "What's a compliment you got recently that you're still thinking about?" },
  { category: "Warm-up", prompt: "What's a small ritual that starts your day off right?" },
  { category: "Warm-up", prompt: "What's your favorite way to spend a lazy Sunday?" },
  { category: "Warm-up", prompt: "What's the last song that got stuck in your head?" },
  { category: "Warm-up", prompt: "What's a random skill you wish you had?" },
  { category: "Warm-up", prompt: "What's your ideal way to unwind after a long week?" },
  { category: "Warm-up", prompt: "What's something that instantly cheers you up when you're grumpy?" },
  { category: "Warm-up", prompt: "What's the best meal you've had recently?" },
  { category: "Warm-up", prompt: "What's a show you're currently obsessed with?" },
  { category: "Warm-up", prompt: "What's something you do purely because it's fun, not useful?" },
  { category: "Warm-up", prompt: "What's your favorite time of day and why?" },
  { category: "Warm-up", prompt: "What's a small luxury you never feel guilty about?" },
  { category: "Warm-up", prompt: "What's the most underrated season and why?" },
  { category: "Warm-up", prompt: "What's a childhood snack you still crave?" },
  { category: "Warm-up", prompt: "What's something that always makes you feel cozy?" },
  { category: "Warm-up", prompt: "What's your favorite kind of weather?" },
  { category: "Warm-up", prompt: "What's a game we could play right now if we wanted to?" },
  { category: "Warm-up", prompt: "What's something you're currently curious about?" },
  { category: "Warm-up", prompt: "What's a small thing you did today that you enjoyed?" },
  { category: "Warm-up", prompt: "What's your favorite way to be surprised?" },
  { category: "Warm-up", prompt: "What's a word or phrase you say way too often?" },
  { category: "Warm-up", prompt: "What's something you collect, even informally?" },
  { category: "Warm-up", prompt: "What does your ideal 'do nothing' day look like?" },
  { category: "Warm-up", prompt: "What's a scent that makes you feel at home?" },
  { category: "Warm-up", prompt: "What's the last thing you looked up out of curiosity?" },
  { category: "Warm-up", prompt: "What's a hobby you'd pick up if time wasn't an issue?" },
  { category: "Warm-up", prompt: "What's something you're low-key excited about this week?" },
  { category: "Warm-up", prompt: "What's your comfort show when you're feeling sick?" },
  { category: "Warm-up", prompt: "What's a tiny thing about today that was actually really nice?" },

  // Appreciation — noticing and naming what you value in each other
  { category: "Appreciation", prompt: "What's something I do that you don't think I realize you notice?" },
  { category: "Appreciation", prompt: "When was the last time you felt really taken care of by me?" },
  { category: "Appreciation", prompt: "What's a quality of mine you wish you had more of?" },
  { category: "Appreciation", prompt: "What's something small I did recently that meant more than I probably knew?" },
  { category: "Appreciation", prompt: "What's a way I've helped you grow since we've been together?" },
  { category: "Appreciation", prompt: "What do you think is my most underrated quality?" },
  { category: "Appreciation", prompt: "What's something you're grateful I've never judged you for?" },
  { category: "Appreciation", prompt: "What's a moment you felt like I really showed up for you?" },
  { category: "Appreciation", prompt: "What's something about how I love you that feels different from how you've been loved before?" },
  { category: "Appreciation", prompt: "What's a strength of mine you lean on without saying it out loud?" },
  { category: "Appreciation", prompt: "What's something I say often that you secretly love hearing?" },
  { category: "Appreciation", prompt: "What's a way you've seen me become a better person?" },
  { category: "Appreciation", prompt: "What's something you'd miss most about me if I were gone for a month?" },
  { category: "Appreciation", prompt: "What's a time I made you feel safe without realizing it?" },
  { category: "Appreciation", prompt: "What's something about us you'd want other couples to have too?" },
  { category: "Appreciation", prompt: "What's something I've forgiven you for that you're grateful I let go of?" },
  { category: "Appreciation", prompt: "What's a way I make hard days easier for you?" },
  { category: "Appreciation", prompt: "What's something about my personality you wish more people got to see?" },
  { category: "Appreciation", prompt: "What's a time I stood up for you that you haven't forgotten?" },
  { category: "Appreciation", prompt: "What's something I do without being asked that you appreciate?" },
  { category: "Appreciation", prompt: "What's a way I've shown up for you that you haven't thanked me for yet?" },
  { category: "Appreciation", prompt: "What's something about my humor that you genuinely love?" },
  { category: "Appreciation", prompt: "What's a time I made you feel less alone?" },
  { category: "Appreciation", prompt: "What's something I do for us that you don't think I get enough credit for?" },
  { category: "Appreciation", prompt: "What's a value of mine you deeply respect?" },
  { category: "Appreciation", prompt: "What's something I've taught you, even without meaning to?" },
  { category: "Appreciation", prompt: "What's a way I make you feel like yourself?" },
  { category: "Appreciation", prompt: "What's something about my patience that stands out to you?" },
  { category: "Appreciation", prompt: "What's a time I believed in you when you didn't believe in yourself?" },
  { category: "Appreciation", prompt: "What's something I do that makes ordinary days feel special?" },
  { category: "Appreciation", prompt: "What's a way I've shown you loyalty that meant a lot?" },
  { category: "Appreciation", prompt: "What's something about how I handle conflict that you admire?" },
  { category: "Appreciation", prompt: "What's a small gesture of mine you replay in your head?" },
  { category: "Appreciation", prompt: "What's something I've given you that isn't a physical thing?" },
  { category: "Appreciation", prompt: "What's a way I've made you feel chosen?" },
  { category: "Appreciation", prompt: "What's something about my resilience that inspires you?" },
  { category: "Appreciation", prompt: "What's a time my support changed how a hard day went?" },
  { category: "Appreciation", prompt: "What's something I do that reminds you why you picked me?" },
  { category: "Appreciation", prompt: "What's a compliment about me you've given someone else?" },
  { category: "Appreciation", prompt: "What's something I do that makes you proud to introduce me to people?" },
  { category: "Appreciation", prompt: "What's a way I've grown that you've quietly noticed?" },
  { category: "Appreciation", prompt: "What's something about how I care for my family or friends that you love?" },
  { category: "Appreciation", prompt: "What's a moment I was gentle with you when I didn't have to be?" },
  { category: "Appreciation", prompt: "What's something I do that makes you feel like a priority?" },
  { category: "Appreciation", prompt: "What's a way I've surprised you with thoughtfulness?" },
  { category: "Appreciation", prompt: "What's something about my curiosity or passions that you find attractive?" },
  { category: "Appreciation", prompt: "What's a time I made a sacrifice for you that you noticed?" },
  { category: "Appreciation", prompt: "What's something I've done that made you trust me more?" },
  { category: "Appreciation", prompt: "What's a habit of mine you hope carries into our future together?" },
  { category: "Appreciation", prompt: "What's something you've never said but always felt about me?" },
  { category: "Appreciation", prompt: "What's a way I make you feel understood without needing to explain yourself?" },
  { category: "Appreciation", prompt: "What's something about how I treat strangers or service workers that you respect?" },
  { category: "Appreciation", prompt: "What's a time I chose you over convenience?" },
  { category: "Appreciation", prompt: "What's something about my ambition that you find quietly inspiring?" },
  { category: "Appreciation", prompt: "What's a way I've made ordinary conflict feel less scary?" },

  // Perspective — how they see you
  { category: "Perspective", prompt: "What's something about me you didn't expect when we first met?" },
  { category: "Perspective", prompt: "What's a moment you felt really proud of me?" },
  { category: "Perspective", prompt: "What do you think I need more of in my life right now?" },
  { category: "Perspective", prompt: "When do you feel most like yourself around me?" },
  { category: "Perspective", prompt: "What's something I do that makes you feel loved?" },
  { category: "Perspective", prompt: "What do you think I'm afraid of that I've never actually said?" },
  { category: "Perspective", prompt: "What's a side of me you only get to see?" },
  { category: "Perspective", prompt: "What do you think I'd be doing right now if we'd never met?" },
  { category: "Perspective", prompt: "What's something you think I underestimate about myself?" },
  { category: "Perspective", prompt: "What's a pattern you've noticed in how I handle stress?" },
  { category: "Perspective", prompt: "What do you think is the biggest way I've changed since you've known me?" },
  { category: "Perspective", prompt: "What's something you think I need to hear right now?" },
  { category: "Perspective", prompt: "What do you think my younger self would think of who I am today?" },
  { category: "Perspective", prompt: "What's a strength of mine you don't think I give myself credit for?" },
  { category: "Perspective", prompt: "What's something you wish I believed about myself?" },
  { category: "Perspective", prompt: "What do you think scares me more than I let on?" },
  { category: "Perspective", prompt: "What's something you think I'm better at than I believe I am?" },
  { category: "Perspective", prompt: "What do you think I'd change about my life if fear wasn't a factor?" },
  { category: "Perspective", prompt: "What's a version of me you only see in private?" },
  { category: "Perspective", prompt: "What do you think I need to forgive myself for?" },
  { category: "Perspective", prompt: "What do you think my biggest blind spot is?" },
  { category: "Perspective", prompt: "What do you think I'd say is my proudest achievement?" },
  { category: "Perspective", prompt: "What's a decision of mine you respected, even if you disagreed?" },
  { category: "Perspective", prompt: "What do you think drives me more than anything else?" },
  { category: "Perspective", prompt: "What's something you think I've never fully processed?" },
  { category: "Perspective", prompt: "What do you think I look like when I'm truly happy?" },
  { category: "Perspective", prompt: "What's a value you think I hold even if I don't say it out loud?" },
  { category: "Perspective", prompt: "What do you think I'm the most misunderstood about?" },
  { category: "Perspective", prompt: "What's something you think I'm still figuring out about myself?" },
  { category: "Perspective", prompt: "What do you think my relationship with my family taught me?" },
  { category: "Perspective", prompt: "What's a moment you saw real growth in me?" },
  { category: "Perspective", prompt: "What do you think I'd regret not doing?" },
  { category: "Perspective", prompt: "What's something you think I do out of love that looks like something else?" },
  { category: "Perspective", prompt: "What do you think I need to hear on my hardest days?" },
  { category: "Perspective", prompt: "What's a strength you think I was born with versus one I built?" },
  { category: "Perspective", prompt: "What do you think scares me about being truly known?" },
  { category: "Perspective", prompt: "What's something you think I've gotten wiser about over time?" },
  { category: "Perspective", prompt: "What do you think I'd change about how I was raised, if I could?" },
  { category: "Perspective", prompt: "What's a way you think I cope that I'm not fully aware of?" },
  { category: "Perspective", prompt: "What do you think my inner voice sounds like on a bad day?" },
  { category: "Perspective", prompt: "What's something you think I secretly wish I was better at?" },
  { category: "Perspective", prompt: "What do you think I need most from the people who love me?" },
  { category: "Perspective", prompt: "What's a talent of mine you think I take for granted?" },
  { category: "Perspective", prompt: "What do you think I'd tell my future self?" },
  { category: "Perspective", prompt: "What's something you think I'm proud of but never say?" },
  { category: "Perspective", prompt: "What do you think is the kindest thing about me?" },
  { category: "Perspective", prompt: "What's a way you think I show love that's easy to miss?" },
  { category: "Perspective", prompt: "What do you think I'm most loyal to?" },
  { category: "Perspective", prompt: "What's something you think I need to let go of?" },
  { category: "Perspective", prompt: "What do you think makes me feel most alive?" },
  { category: "Perspective", prompt: "What do you think is the most consistent thing about me, no matter the situation?" },
  { category: "Perspective", prompt: "What's a way you think I've protected my heart without realizing it?" },
  { category: "Perspective", prompt: "What do you think I'm most likely to regret if I don't address it now?" },
  { category: "Perspective", prompt: "What's something you think I do purely out of habit, not choice?" },
  { category: "Perspective", prompt: "What do you think would surprise people most about who I am at home?" },

  // Connection — about the two of you together
  { category: "Connection", prompt: "What's something you've never told me but wanted to?" },
  { category: "Connection", prompt: "What's a fear you have about us that you don't talk about?" },
  { category: "Connection", prompt: "What does feeling truly understood look like to you?" },
  { category: "Connection", prompt: "What's a way I could support you better right now?" },
  { category: "Connection", prompt: "What's something you need to hear from me more often?" },
  { category: "Connection", prompt: "What's an argument we had that you think about differently now?" },
  { category: "Connection", prompt: "What's something you need from me when you're upset that you don't always ask for?" },
  { category: "Connection", prompt: "What's a way we've grown closer that surprised you?" },
  { category: "Connection", prompt: "What's something you assume I know but have never actually said out loud?" },
  { category: "Connection", prompt: "What's a habit of mine that's hard for you, and how do you usually handle it?" },
  { category: "Connection", prompt: "What's something you want us to get better at together?" },
  { category: "Connection", prompt: "When do you feel the most distant from me, even if things are fine?" },
  { category: "Connection", prompt: "What's a way you show love that you're not sure I fully notice?" },
  { category: "Connection", prompt: "What's something about how we communicate you'd change if you could?" },
  { category: "Connection", prompt: "What's a moment you felt closest to me this year?" },
  { category: "Connection", prompt: "What's something you wish we talked about more often?" },
  { category: "Connection", prompt: "What's a way we've learned to fight fairer over time?" },
  { category: "Connection", prompt: "What's something you need reassurance about that you rarely bring up?" },
  { category: "Connection", prompt: "What's a silent way we comfort each other that words couldn't do justice?" },
  { category: "Connection", prompt: "What's something about 'us' you'd want to protect no matter what?" },
  { category: "Connection", prompt: "What's something you want us to say out loud more often?" },
  { category: "Connection", prompt: "What's a way you feel most 'in sync' with me?" },
  { category: "Connection", prompt: "What's something you wish we protected more fiercely?" },
  { category: "Connection", prompt: "What's a ritual that keeps us close during busy weeks?" },
  { category: "Connection", prompt: "What's something that instantly resets us after a rough patch?" },
  { category: "Connection", prompt: "What's a way you want to be pursued, even years in?" },
  { category: "Connection", prompt: "What's something you've learned about love from being with me?" },
  { category: "Connection", prompt: "What's a way we balance each other out?" },
  { category: "Connection", prompt: "What's something you need from me during big life changes?" },
  { category: "Connection", prompt: "What's a fear about 'us' that's actually softened over time?" },
  { category: "Connection", prompt: "What's something you want us to never stop doing, even when it's inconvenient?" },
  { category: "Connection", prompt: "What's a way you'd like us to check in emotionally more often?" },
  { category: "Connection", prompt: "What's something about our dynamic that took time to build trust around?" },
  { category: "Connection", prompt: "What's a way you feel most emotionally safe with me?" },
  { category: "Connection", prompt: "What's something you want me to remember about you on my worst days?" },
  { category: "Connection", prompt: "What's a way distance, physical or emotional, has taught us something?" },
  { category: "Connection", prompt: "What's something small that always brings us back together?" },
  { category: "Connection", prompt: "What's a way you want us to grow as a team, not just individuals?" },
  { category: "Connection", prompt: "What's something you need from me that has nothing to do with fixing a problem?" },
  { category: "Connection", prompt: "What's a way our instincts differ, and how do we bridge that?" },
  { category: "Connection", prompt: "What's something you wish I understood faster during disagreements?" },
  { category: "Connection", prompt: "What's a moment you felt like we were truly a team?" },
  { category: "Connection", prompt: "What's something that makes you feel chosen by me every day?" },
  { category: "Connection", prompt: "What's a way we've learned to repair after hurting each other?" },
  { category: "Connection", prompt: "What's something you want us to be intentional about this year?" },
  { category: "Connection", prompt: "What's a boundary in our relationship you're proud we set?" },
  { category: "Connection", prompt: "What's something you never want us to become as a couple?" },
  { category: "Connection", prompt: "What's a way you'd like affection to look different day-to-day?" },
  { category: "Connection", prompt: "What's something about trust that's still being built between us?" },
  { category: "Connection", prompt: "What's a way you know, without me saying it, that I love you?" },
  { category: "Connection", prompt: "What's a way you'd like us to make repair after conflict feel less heavy?" },
  { category: "Connection", prompt: "What's something about shared responsibility you want us to talk through more?" },
  { category: "Connection", prompt: "What's a way our humor has become its own language?" },
  { category: "Connection", prompt: "What's something you want us to be unapologetic about together?" },
  { category: "Connection", prompt: "What's a way you want to be chosen by me, especially on ordinary days?" },

  // Reflection — inward-looking, personal growth
  { category: "Reflection", prompt: "What's something you've changed your mind about recently?" },
  { category: "Reflection", prompt: "What's a version of yourself you're trying to grow into?" },
  { category: "Reflection", prompt: "What's something you're still healing from?" },
  { category: "Reflection", prompt: "What does home mean to you?" },
  { category: "Reflection", prompt: "What's something you hope never changes between us?" },
  { category: "Reflection", prompt: "What's a belief you grew up with that you've since let go of?" },
  { category: "Reflection", prompt: "What's something you're proud of that no one really congratulated you for?" },
  { category: "Reflection", prompt: "What's a fear that's quietly shaped a lot of your decisions?" },
  { category: "Reflection", prompt: "What's something you needed to hear as a kid that nobody said?" },
  { category: "Reflection", prompt: "What's a mistake that taught you the most about yourself?" },
  { category: "Reflection", prompt: "What's something you're working on that feels slow but matters?" },
  { category: "Reflection", prompt: "What's a part of yourself you used to hide that you don't anymore?" },
  { category: "Reflection", prompt: "What does being loved well actually feel like to you?" },
  { category: "Reflection", prompt: "What's something you forgive yourself for now that you didn't used to?" },
  { category: "Reflection", prompt: "What's a question you wish someone would ask you more often?" },
  { category: "Reflection", prompt: "What's a lesson you keep having to relearn?" },
  { category: "Reflection", prompt: "What's something you used to want that you don't want anymore?" },
  { category: "Reflection", prompt: "What's a part of your personality you inherited that you have mixed feelings about?" },
  { category: "Reflection", prompt: "What's something you're quietly working through right now?" },
  { category: "Reflection", prompt: "What's a truth about yourself you've only recently accepted?" },
  { category: "Reflection", prompt: "What's a story you tell about yourself that might not be fully true anymore?" },
  { category: "Reflection", prompt: "What's something you're unlearning right now?" },
  { category: "Reflection", prompt: "What's a comparison you make to others that isn't fair to you?" },
  { category: "Reflection", prompt: "What's something about ambition that's shifted for you?" },
  { category: "Reflection", prompt: "What's a version of 'success' you no longer chase?" },
  { category: "Reflection", prompt: "What's something you thought would fix you but didn't?" },
  { category: "Reflection", prompt: "What's a coping mechanism you're trying to replace with something healthier?" },
  { category: "Reflection", prompt: "What's something about rest you're still learning to allow yourself?" },
  { category: "Reflection", prompt: "What's a fear of failure that's quietly shaped your choices?" },
  { category: "Reflection", prompt: "What's something you know intellectually but haven't felt yet?" },
  { category: "Reflection", prompt: "What's a way you've become more patient with yourself?" },
  { category: "Reflection", prompt: "What's something you used to apologize for that you don't anymore?" },
  { category: "Reflection", prompt: "What's a limiting belief you're actively challenging?" },
  { category: "Reflection", prompt: "What's something about your identity that's evolved the most?" },
  { category: "Reflection", prompt: "What's a way perfectionism has shown up in your life?" },
  { category: "Reflection", prompt: "What's something you're proud you said no to?" },
  { category: "Reflection", prompt: "What's a truth about your past you've made peace with?" },
  { category: "Reflection", prompt: "What's something you're learning to receive, not just give?" },
  { category: "Reflection", prompt: "What's a boundary you're proud you finally set?" },
  { category: "Reflection", prompt: "What's something about vulnerability that's gotten easier?" },
  { category: "Reflection", prompt: "What's a habit you're trying to build that reflects who you want to be?" },
  { category: "Reflection", prompt: "What's something about control you're learning to release?" },
  { category: "Reflection", prompt: "What's a fear you're slowly becoming less afraid of?" },
  { category: "Reflection", prompt: "What's something you've stopped explaining or justifying?" },
  { category: "Reflection", prompt: "What's a way you show yourself compassion now that you didn't before?" },
  { category: "Reflection", prompt: "What's something about your body or health you're making peace with?" },
  { category: "Reflection", prompt: "What's a lesson from a hard year that actually paid off?" },
  { category: "Reflection", prompt: "What's something you're grateful your younger self pushed through?" },
  { category: "Reflection", prompt: "What's a part of your story you're ready to stop hiding?" },
  { category: "Reflection", prompt: "What's something you hope to understand about yourself five years from now?" },
  { category: "Reflection", prompt: "What's something you're proud you didn't rush?" },
  { category: "Reflection", prompt: "What's a way you've redefined strength for yourself?" },
  { category: "Reflection", prompt: "What's something about discipline versus self-compassion you're balancing?" },
  { category: "Reflection", prompt: "What's a version of rest that still feels new to you?" },
  { category: "Reflection", prompt: "What's something you're learning to say no to without guilt?" },

  // Memories — nostalgia, shared or personal
  { category: "Memories", prompt: "What's the first thing you remember thinking about me?" },
  { category: "Memories", prompt: "What's a memory of us you replay when you need to smile?" },
  { category: "Memories", prompt: "What's a childhood memory that still shapes how you see the world?" },
  { category: "Memories", prompt: "What's the most nervous you've ever been around me?" },
  { category: "Memories", prompt: "What's a moment early on when you realized you were falling for me?" },
  { category: "Memories", prompt: "What's a trip or day together you wish you could relive exactly as it was?" },
  { category: "Memories", prompt: "What's something we laughed about that still gets you if you think about it?" },
  { category: "Memories", prompt: "What's a memory with your family that you hold onto tightly?" },
  { category: "Memories", prompt: "What's the hardest we've ever laughed together?" },
  { category: "Memories", prompt: "What's a version of 'us' from earlier on that you miss?" },
  { category: "Memories", prompt: "What's something from your childhood you want to give me a better sense of?" },
  { category: "Memories", prompt: "What's a moment you felt unexpectedly proud of us as a couple?" },
  { category: "Memories", prompt: "What's the most romantic thing that's happened between us, in your opinion?" },
  { category: "Memories", prompt: "What's a memory that still stings a little, even if it shouldn't anymore?" },
  { category: "Memories", prompt: "What's something about how we met that you didn't appreciate until later?" },
  { category: "Memories", prompt: "What's a moment with me you didn't realize was special until later?" },
  { category: "Memories", prompt: "What's the most 'us' inside joke we have?" },
  { category: "Memories", prompt: "What's a memory of your own growing up that you smile thinking about?" },
  { category: "Memories", prompt: "What's a time I surprised you in a good way?" },
  { category: "Memories", prompt: "What's a small ordinary moment with me that you never want to forget?" },
  { category: "Memories", prompt: "What's the first compliment you remember me giving you?" },
  { category: "Memories", prompt: "What's a memory of us that felt like a movie moment?" },
  { category: "Memories", prompt: "What's the silliest fight we've ever had, looking back?" },
  { category: "Memories", prompt: "What's a memory of meeting my family or friends for the first time?" },
  { category: "Memories", prompt: "What's something from a hard time in our relationship you're glad we got through?" },
  { category: "Memories", prompt: "What's a memory tied to a meal or food that means something to us?" },
  { category: "Memories", prompt: "What's the first time you felt truly 'we' instead of 'you and me'?" },
  { category: "Memories", prompt: "What's a trip or journey memory that stands out?" },
  { category: "Memories", prompt: "What's a memory tied to a song that's 'ours'?" },
  { category: "Memories", prompt: "What's something from your past relationships that shaped how you love now?" },
  { category: "Memories", prompt: "What's a memory of us being proud of each other in public?" },
  { category: "Memories", prompt: "What's a rainy day memory with me you still think about?" },
  { category: "Memories", prompt: "What's the most spontaneous thing we've ever done together?" },
  { category: "Memories", prompt: "What's a memory where you saw a completely different side of me?" },
  { category: "Memories", prompt: "What's something from your teenage years that still makes you cringe fondly?" },
  { category: "Memories", prompt: "What's a memory of us taking care of each other while sick?" },
  { category: "Memories", prompt: "What's the first place that felt like 'ours' together?" },
  { category: "Memories", prompt: "What's a memory of celebrating something small that felt huge?" },
  { category: "Memories", prompt: "What's something about a grandparent or older relative you cherish?" },
  { category: "Memories", prompt: "What's a memory of us navigating a stressful event as a team?" },
  { category: "Memories", prompt: "What's the funniest thing that's ever happened on a date with me?" },
  { category: "Memories", prompt: "What's a memory that makes you appreciate how far we've come?" },
  { category: "Memories", prompt: "What's something nostalgic about your old room or childhood home?" },
  { category: "Memories", prompt: "What's a memory of us disagreeing and still respecting each other?" },
  { category: "Memories", prompt: "What's the most 'in love' you've ever felt in a single moment?" },
  { category: "Memories", prompt: "What's a memory involving a pet, ours or someone else's, that stuck with you?" },
  { category: "Memories", prompt: "What's something about an old friendship that still shapes you?" },
  { category: "Memories", prompt: "What's a holiday memory with me that stands out?" },
  { category: "Memories", prompt: "What's a memory of us being goofy in public without caring?" },
  { category: "Memories", prompt: "What's the last memory that made you think 'I want to remember this forever'?" },
  { category: "Memories", prompt: "What's a memory where you felt unconditionally accepted by me?" },
  { category: "Memories", prompt: "What's something from early dating that still makes you nostalgic?" },
  { category: "Memories", prompt: "What's a memory of overcoming something hard together that you're proud of?" },
  { category: "Memories", prompt: "What's a small everyday memory that quietly means a lot?" },
  { category: "Memories", prompt: "What's a memory that changed how you saw your own strength?" },

  // Future — hopes, plans, hypotheticals
  { category: "Future", prompt: "What does a perfect ordinary day with me look like ten years from now?" },
  { category: "Future", prompt: "What's something you want us to try together that we haven't yet?" },
  { category: "Future", prompt: "What's a fear you have about the future that you rarely say out loud?" },
  { category: "Future", prompt: "What's a tradition you want us to build together?" },
  { category: "Future", prompt: "What does 'success' look like to you five years from now?" },
  { category: "Future", prompt: "What's something you hope I never stop doing?" },
  { category: "Future", prompt: "What's a version of our life together that would make you feel completely content?" },
  { category: "Future", prompt: "What's something you want to learn or get better at together?" },
  { category: "Future", prompt: "What's a place you'd want us to live at some point in our lives?" },
  { category: "Future", prompt: "What's something you hope people say about us after knowing us for years?" },
  { category: "Future", prompt: "What's a way you hope we handle hard times better as we go?" },
  { category: "Future", prompt: "What's something on your bucket list you haven't told me about?" },
  { category: "Future", prompt: "What kind of parent, if any, do you picture yourself being?" },
  { category: "Future", prompt: "What's something you want to be different about you a year from now?" },
  { category: "Future", prompt: "What's a promise you want to make to me right now?" },
  { category: "Future", prompt: "What's something you hope we never take for granted?" },
  { category: "Future", prompt: "What's a fear about growing older together you rarely voice?" },
  { category: "Future", prompt: "What's a version of adventure you want more of in our life?" },
  { category: "Future", prompt: "What's something you hope stays exactly the same about us?" },
  { category: "Future", prompt: "What's a way you hope we show up for each other in hard seasons ahead?" },
  { category: "Future", prompt: "What's something you hope becomes easier for us with time?" },
  { category: "Future", prompt: "What's a version of old age you picture with me?" },
  { category: "Future", prompt: "What's something you want to protect us from as life gets busier?" },
  { category: "Future", prompt: "What's a skill you hope we both get better at together?" },
  { category: "Future", prompt: "What's something about raising kids, if that's part of our future, that excites you?" },
  { category: "Future", prompt: "What's a way you hope we handle money, whether differently or the same as now?" },
  { category: "Future", prompt: "What's something you hope we teach any kids we might have?" },
  { category: "Future", prompt: "What's a way you picture us celebrating milestones years from now?" },
  { category: "Future", prompt: "What's something you hope never becomes 'routine' between us?" },
  { category: "Future", prompt: "What's a place you haven't been that you want to experience with me?" },
  { category: "Future", prompt: "What's something about getting older together that excites rather than scares you?" },
  { category: "Future", prompt: "What's a way you hope our communication evolves as we age?" },
  { category: "Future", prompt: "What's something you want us to prioritize that we currently don't?" },
  { category: "Future", prompt: "What's a hope you have for how we'll support each other's ambitions?" },
  { category: "Future", prompt: "What's something you want our home, wherever it is, to always feel like?" },
  { category: "Future", prompt: "What's a way you hope we stay curious about each other?" },
  { category: "Future", prompt: "What's something you want to make sure we never stop doing for fun?" },
  { category: "Future", prompt: "What's a hope you have for our friendships in the future?" },
  { category: "Future", prompt: "What's something about health or wellness you hope we build together?" },
  { category: "Future", prompt: "What's a future conversation you're a little nervous but ready to have?" },
  { category: "Future", prompt: "What's something you hope people notice about us when we're old?" },
  { category: "Future", prompt: "What's a way you picture us handling a major life setback together?" },
  { category: "Future", prompt: "What's something you want to say yes to more in the coming years?" },
  { category: "Future", prompt: "What's a hope you have for how we'll comfort each other decades from now?" },
  { category: "Future", prompt: "What's something you want to be brave enough to try with me?" },
  { category: "Future", prompt: "What's a version of legacy that matters to you?" },
  { category: "Future", prompt: "What's something you hope we never have to compromise on?" },
  { category: "Future", prompt: "What's a way you picture us helping others together someday?" },
  { category: "Future", prompt: "What's something about independence you hope we always protect for each other?" },
  { category: "Future", prompt: "What's a hope for us that feels a little vulnerable to say out loud?" },
  { category: "Future", prompt: "What's something you hope becomes a defining trait of our relationship over time?" },
  { category: "Future", prompt: "What's a way you hope we handle success without losing perspective?" },
  { category: "Future", prompt: "What's something you hope we're braver about as the years go on?" },
  { category: "Future", prompt: "What's a way you picture comforting each other through loss someday?" },
  { category: "Future", prompt: "What's something about partnership you hope only deepens with time?" },

  // Vulnerability — harder, deeper questions
  { category: "Vulnerability", prompt: "What's something you're scared to admit you need from me?" },
  { category: "Vulnerability", prompt: "What's a way you protect yourself from getting hurt, even by me?" },
  { category: "Vulnerability", prompt: "What's something about yourself you're still learning to accept?" },
  { category: "Vulnerability", prompt: "What's the loneliest you've ever felt, even around other people?" },
  { category: "Vulnerability", prompt: "What's something you've never said out loud because it felt too honest?" },
  { category: "Vulnerability", prompt: "What's a moment you felt truly unlovable, even briefly?" },
  { category: "Vulnerability", prompt: "What's something you need me to be patient with you about?" },
  { category: "Vulnerability", prompt: "What's a way you sometimes sabotage good things without meaning to?" },
  { category: "Vulnerability", prompt: "What's something you're afraid I'll find out about you?" },
  { category: "Vulnerability", prompt: "What's a wound from your past that shows up in how you love people now?" },
  { category: "Vulnerability", prompt: "What's something you wish you could let yourself feel more openly?" },
  { category: "Vulnerability", prompt: "What's a moment recently you needed comfort but didn't ask for it?" },
  { category: "Vulnerability", prompt: "What's something you're proud of surviving that you don't talk about?" },
  { category: "Vulnerability", prompt: "What's a fear about yourself you hope isn't true?" },
  { category: "Vulnerability", prompt: "What's something you need to hear right now, even if it's hard to ask for?" },
  { category: "Vulnerability", prompt: "What's something you're afraid to want out loud?" },
  { category: "Vulnerability", prompt: "What's a way you've learned to hide pain that you're trying to unlearn?" },
  { category: "Vulnerability", prompt: "What's something you need me to understand about how you were raised?" },
  { category: "Vulnerability", prompt: "What's a moment you felt truly seen, and by whom?" },
  { category: "Vulnerability", prompt: "What's something you hope I never give up on with you?" },
  { category: "Vulnerability", prompt: "What's something you're afraid would change if you were fully honest with me?" },
  { category: "Vulnerability", prompt: "What's a way you've felt like a burden, even if you weren't?" },
  { category: "Vulnerability", prompt: "What's something about your appearance you're working on accepting?" },
  { category: "Vulnerability", prompt: "What's a time you needed rescuing and didn't know how to ask?" },
  { category: "Vulnerability", prompt: "What's something you're afraid isn't reciprocated the way you give it?" },
  { category: "Vulnerability", prompt: "What's a way rejection from your past still echoes today?" },
  { category: "Vulnerability", prompt: "What's something you feel guilty about that you've never said aloud?" },
  { category: "Vulnerability", prompt: "What's a way you numb hard feelings instead of facing them?" },
  { category: "Vulnerability", prompt: "What's something you're afraid makes you 'too much' or 'not enough'?" },
  { category: "Vulnerability", prompt: "What's a time you felt betrayed that still affects your trust?" },
  { category: "Vulnerability", prompt: "What's something about intimacy that's harder for you than it looks?" },
  { category: "Vulnerability", prompt: "What's a way you people-please that you're trying to unlearn?" },
  { category: "Vulnerability", prompt: "What's something you're scared to need because you're used to being the strong one?" },
  { category: "Vulnerability", prompt: "What's a memory of shame you've never fully shared with anyone?" },
  { category: "Vulnerability", prompt: "What's something you're afraid of repeating from your parents' relationship?" },
  { category: "Vulnerability", prompt: "What's a way you self-sabotage when things are going too well?" },
  { category: "Vulnerability", prompt: "What's something you wish you could cry about more openly?" },
  { category: "Vulnerability", prompt: "What's a fear about being truly known that you're facing right now?" },
  { category: "Vulnerability", prompt: "What's something about your worth you're still trying to believe?" },
  { category: "Vulnerability", prompt: "What's a way loneliness shows up for you even in a relationship?" },
  { category: "Vulnerability", prompt: "What's something you're afraid to grieve because it feels indulgent?" },
  { category: "Vulnerability", prompt: "What's a time you masked pain with humor instead of naming it?" },
  { category: "Vulnerability", prompt: "What's something you need permission to feel angry about?" },
  { category: "Vulnerability", prompt: "What's a way you've confused being needed with being loved?" },
  { category: "Vulnerability", prompt: "What's something about control that's really about fear underneath?" },
  { category: "Vulnerability", prompt: "What's a part of you that you're scared isn't lovable?" },
  { category: "Vulnerability", prompt: "What's something you've never forgiven yourself for?" },
  { category: "Vulnerability", prompt: "What's a way you test people before trusting them, even me?" },
  { category: "Vulnerability", prompt: "What's something you wish someone had protected you from?" },
  { category: "Vulnerability", prompt: "What's a truth about your heart right now that you haven't said aloud?" },
  { category: "Vulnerability", prompt: "What's something you're afraid to admit you're still figuring out about love?" },
  { category: "Vulnerability", prompt: "What's a way you've mistaken silence for strength?" },
  { category: "Vulnerability", prompt: "What's something you wish you didn't have to justify feeling?" },
  { category: "Vulnerability", prompt: "What's a fear about disappointing me that you rarely say?" },
  { category: "Vulnerability", prompt: "What's something tender about you that takes real trust to show?" },

  // Playful — light, fun, a little silly
  { category: "Playful", prompt: "If we swapped lives for a day, what's the first thing you'd do as me?" },
  { category: "Playful", prompt: "What's the most ridiculous thing you'd do for a million dollars right now?" },
  { category: "Playful", prompt: "What's a superpower you'd want, just for the two of us?" },
  { category: "Playful", prompt: "If you had to describe our relationship as a genre of movie, what would it be?" },
  { category: "Playful", prompt: "What's the weirdest food combo you secretly love?" },
  { category: "Playful", prompt: "If we started a business together tomorrow, what would it be?" },
  { category: "Playful", prompt: "What's a nickname you've never told me you thought of for me?" },
  { category: "Playful", prompt: "What's the most chaotic thing we could do on a random Tuesday?" },
  { category: "Playful", prompt: "If our relationship had a theme song, what would it be?" },
  { category: "Playful", prompt: "What's a hill you'll die on that's completely trivial?" },
  { category: "Playful", prompt: "What's something you think we'd be unreasonably good at as a duo?" },
  { category: "Playful", prompt: "If you could give past-us one piece of advice, what would it be?" },
  { category: "Playful", prompt: "What's the most 'you' purchase you've ever made?" },
  { category: "Playful", prompt: "What's a weirdly specific dream job you've fantasized about?" },
  { category: "Playful", prompt: "If we had a reality show, what would the tagline be?" },
  { category: "Playful", prompt: "What's the most useless talent you're weirdly proud of?" },
  { category: "Playful", prompt: "If you had a warning label, what would it say?" },
  { category: "Playful", prompt: "What's a food you'd fight someone over?" },
  { category: "Playful", prompt: "If we were cartoon characters, what would our catchphrases be?" },
  { category: "Playful", prompt: "What's the most 'extra' thing you'd do to impress me?" },
  { category: "Playful", prompt: "If you could only communicate in movie quotes for a day, which movie would you pick?" },
  { category: "Playful", prompt: "What's an object in our home that has main character energy?" },
  { category: "Playful", prompt: "If our love story were a video game, what level would we be on?" },
  { category: "Playful", prompt: "What's the pettiest thing you've ever been annoyed about?" },
  { category: "Playful", prompt: "If you had to DJ our next road trip, what's the first song?" },
  { category: "Playful", prompt: "What's a trend you refuse to admit you liked?" },
  { category: "Playful", prompt: "If we had a secret handshake, what would it involve?" },
  { category: "Playful", prompt: "What's the most dramatic reaction you've had to something small?" },
  { category: "Playful", prompt: "If you were a kitchen appliance, which one and why?" },
  { category: "Playful", prompt: "What's a conspiracy theory you find weirdly fun to think about?" },
  { category: "Playful", prompt: "If our relationship got an online review, what would it say?" },
  { category: "Playful", prompt: "What's the boldest fashion choice you've ever made?" },
  { category: "Playful", prompt: "If you had to give a talk on any topic, what would it be?" },
  { category: "Playful", prompt: "What's a food you refuse to eat no matter what?" },
  { category: "Playful", prompt: "If we were villains in a movie, what would our evil plan be?" },
  { category: "Playful", prompt: "What's the most 'you' way to spend an unexpected free day?" },
  { category: "Playful", prompt: "If you could instantly master one useless skill, what would it be?" },
  { category: "Playful", prompt: "What's a weirdly specific pet peeve you have?" },
  { category: "Playful", prompt: "If we opened a restaurant together, what would we serve?" },
  { category: "Playful", prompt: "What's the most competitive you've ever gotten over a board game?" },
  { category: "Playful", prompt: "If you had a mascot, what animal would it be and why?" },
  { category: "Playful", prompt: "What's a childhood cartoon you'd defend passionately?" },
  { category: "Playful", prompt: "If we time-traveled to any decade, which would you pick and why?" },
  { category: "Playful", prompt: "What's the weirdest thing you've ever found genuinely funny?" },
  { category: "Playful", prompt: "If our life were a sitcom, what would the theme song sound like?" },
  { category: "Playful", prompt: "What's a food combo you think is underrated?" },
  { category: "Playful", prompt: "If you had to survive a wild scenario with only three items, what would you pick?" },
  { category: "Playful", prompt: "What's the most chaotic vacation idea you secretly want to try?" },
  { category: "Playful", prompt: "If we were sorted into fictional houses or teams, what would we be and why?" },
  { category: "Playful", prompt: "What's a completely unnecessary thing you're stubborn about?" },

  // Communication — how you talk, listen, and show up for each other
  { category: "Communication", prompt: "What's something you wish I asked you more often?" },
  { category: "Communication", prompt: "What's a way you'd like me to check in with you during stressful weeks?" },
  { category: "Communication", prompt: "What's something you need me to just listen to, not fix?" },
  { category: "Communication", prompt: "What's a topic you avoid bringing up because it feels risky?" },
  { category: "Communication", prompt: "What's a way you'd like us to handle disagreements differently?" },
  { category: "Communication", prompt: "What's something you wish you were better at telling me?" },
  { category: "Communication", prompt: "What's a signal you give when you need space that I might be missing?" },
  { category: "Communication", prompt: "What's something you want me to keep asking about, even if you brush it off at first?" },
  { category: "Communication", prompt: "What's a way silence between us feels different depending on the day?" },
  { category: "Communication", prompt: "What's something you need me to say more plainly instead of hinting at?" },
  { category: "Communication", prompt: "What's a boundary you want us to respect more consistently?" },
  { category: "Communication", prompt: "What's something you appreciate about how I apologize, or wish were different?" },
  { category: "Communication", prompt: "What's a way you'd like to celebrate wins together more?" },
  { category: "Communication", prompt: "What's something you want to check in about that's been sitting quietly?" },
  { category: "Communication", prompt: "What's a conversation we keep putting off that we should actually have?" },
  { category: "Communication", prompt: "What's something you wish I noticed without you having to point it out?" },
  { category: "Communication", prompt: "What's a way you'd like feedback delivered so it lands better with you?" },
  { category: "Communication", prompt: "What's something you need after an argument before you're ready to reconnect?" },
  { category: "Communication", prompt: "What's a phrase that instantly makes you feel dismissed?" },
  { category: "Communication", prompt: "What's a phrase that instantly makes you feel heard?" },
  { category: "Communication", prompt: "What's something you wish I asked before jumping to advice?" },
  { category: "Communication", prompt: "What's a way you'd like me to bring up something that's bothering me?" },
  { category: "Communication", prompt: "What's something you need to feel safe being fully honest with me?" },
  { category: "Communication", prompt: "What's a communication habit from your family you're trying not to repeat?" },
  { category: "Communication", prompt: "What's something you wish we scheduled time to talk about regularly?" },
  { category: "Communication", prompt: "What's a way you'd like to be comforted differently depending on the day?" },
  { category: "Communication", prompt: "What's something you need me to ask twice because you don't always answer honestly the first time?" },
  { category: "Communication", prompt: "What's a way tone matters more to you than the actual words?" },
  { category: "Communication", prompt: "What's something you wish I understood about how you process emotions?" },
  { category: "Communication", prompt: "What's a way you'd like disagreements to end, even if unresolved?" },
  { category: "Communication", prompt: "What's something you need from me before a hard conversation, not just during it?" },
  { category: "Communication", prompt: "What's a way you show you're upset that isn't always obvious to me?" },
  { category: "Communication", prompt: "What's something you wish I'd stop assuming about how you feel?" },
  { category: "Communication", prompt: "What's a phrase you want us to adopt for when one of us needs space?" },
  { category: "Communication", prompt: "What's something you need to hear after you've made a mistake?" },
  { category: "Communication", prompt: "What's a way you'd like praise or celebration to look, specifically from me?" },
  { category: "Communication", prompt: "What's something you wish I checked in about more during busy seasons?" },
  { category: "Communication", prompt: "What's a way silence from me makes you feel, and what do you need instead?" },
  { category: "Communication", prompt: "What's something you need reassurance about that feels silly to ask directly?" },
  { category: "Communication", prompt: "What's a communication pattern of ours you're proud we've improved?" },
  { category: "Communication", prompt: "What's something you wish I remembered mid-argument, even when it's tense?" },
  { category: "Communication", prompt: "What's a way you'd like to give feedback to me that you're nervous to try?" },
  { category: "Communication", prompt: "What's something you need before you can fully let your guard down in a talk?" },
  { category: "Communication", prompt: "What's a way texting versus talking in person changes how you communicate?" },
  { category: "Communication", prompt: "What's something you wish I asked about your day beyond 'how was it'?" },
  { category: "Communication", prompt: "What's a way you'd like to handle it when we're both right but still stuck?" },
  { category: "Communication", prompt: "What's something you need to feel like a disagreement isn't a threat to us?" },
  { category: "Communication", prompt: "What's a way you'd like affection and hard conversations to coexist better?" },
  { category: "Communication", prompt: "What's something you wish I understood about your need for space?" },
  { category: "Communication", prompt: "What's a communication style from your past relationships you're glad isn't part of ours?" },

  // Friendship — thoughtful questions for friends who want to go deeper
  { category: "Friendship", prompt: "What's something you've always wanted to tell me but never found the right moment?" },
  { category: "Friendship", prompt: "When did you first feel like we were actually friends, not just people who knew each other?" },
  { category: "Friendship", prompt: "What's a first impression you had of me that turned out to be completely wrong?" },
  { category: "Friendship", prompt: "What do you think I misunderstand about you?" },
  { category: "Friendship", prompt: "What's something you admire about me that you'd feel awkward saying to my face?" },
  { category: "Friendship", prompt: "What's a way I've influenced you without realizing it?" },
  { category: "Friendship", prompt: "When was the last time you felt genuinely supported by me?" },
  { category: "Friendship", prompt: "What's something you're going through right now that you haven't told many people about?" },
  { category: "Friendship", prompt: "What do you need from your friends that you rarely ask for?" },
  { category: "Friendship", prompt: "What's a friendship from your past that changed how you show up in friendships now?" },
  { category: "Friendship", prompt: "How do you know when you can really trust someone?" },
  { category: "Friendship", prompt: "What's something people assume about you that isn't true?" },
  { category: "Friendship", prompt: "What part of your life do you feel most alone in?" },
  { category: "Friendship", prompt: "What's a compliment you've received that stuck with you for years?" },
  { category: "Friendship", prompt: "What do you think your closest friends would say is your best quality?" },
  { category: "Friendship", prompt: "What's a fear you have about our friendship?" },
  { category: "Friendship", prompt: "When have you felt let down by a friend, and what did it teach you?" },
  { category: "Friendship", prompt: "What's something you wish I asked you about more often?" },
  { category: "Friendship", prompt: "What version of yourself do you feel like around me?" },
  { category: "Friendship", prompt: "What's a dream you've mostly stopped talking about but haven't let go of?" },
  { category: "Friendship", prompt: "What's the hardest year of your life been so far, and are you out of it?" },
  { category: "Friendship", prompt: "What do you think I'd be surprised to learn about your childhood?" },
  { category: "Friendship", prompt: "What's a belief you hold now that would shock the person you were five years ago?" },
  { category: "Friendship", prompt: "When do you feel most like yourself?" },
  { category: "Friendship", prompt: "What's something you're proud of that you don't get to talk about much?" },
  { category: "Friendship", prompt: "What's a way you've changed that you're still getting used to?" },
  { category: "Friendship", prompt: "What do you think is the biggest difference between how you seem and how you actually feel?" },
  { category: "Friendship", prompt: "What's a conversation you've been avoiding, with anyone?" },
  { category: "Friendship", prompt: "What do you need more of in your life right now?" },
  { category: "Friendship", prompt: "What's something you're afraid people would think if they really knew you?" },
  { category: "Friendship", prompt: "Who has shaped you the most, and do they know it?" },
  { category: "Friendship", prompt: "What's a moment you felt truly seen by someone?" },
  { category: "Friendship", prompt: "What's something you're still carrying that you'd like to put down?" },
  { category: "Friendship", prompt: "How have your friendships changed as you've gotten older?" },
  { category: "Friendship", prompt: "What's a risk you took that you're glad you took?" },
  { category: "Friendship", prompt: "What's a risk you didn't take that you still think about?" },
  { category: "Friendship", prompt: "What do you think people get wrong about what you want out of life?" },
  { category: "Friendship", prompt: "What's the kindest thing someone has done for you?" },
  { category: "Friendship", prompt: "When was the last time you cried, and what was it about?" },
  { category: "Friendship", prompt: "What's something you're figuring out about yourself right now?" },
  { category: "Friendship", prompt: "What do you wish you were braver about?" },
  { category: "Friendship", prompt: "What's a part of your life you feel like you're just performing?" },
  { category: "Friendship", prompt: "What do you think I could learn from you?" },
  { category: "Friendship", prompt: "What's something you'd want me to do if you were going through a hard time and hiding it?" },
  { category: "Friendship", prompt: "What's a memory of us that means more to you than I might realize?" },
  { category: "Friendship", prompt: "What's something you've forgiven someone for that took a long time?" },
  { category: "Friendship", prompt: "What do you think your life will look like in ten years, and how do you feel about that?" },
  { category: "Friendship", prompt: "What's a question you wish people asked you instead of the usual small talk?" },
  { category: "Friendship", prompt: "What makes you feel closest to someone?" },
  { category: "Friendship", prompt: "What's something you've never said out loud but think about often?" },
  { category: "Friendship", prompt: "What do you think you're underestimating about yourself?" },
  { category: "Friendship", prompt: "What's a way I could be a better friend to you?" },
  { category: "Friendship", prompt: "What's something good happening in your life right now that you haven't celebrated enough?" },
  { category: "Friendship", prompt: "What's a truth about your family you've made peace with?" },
  { category: "Friendship", prompt: "If we drifted apart, what do you think would cause it, and how do we stop that?" },
  { category: "Friendship", prompt: "What do you hope stays the same about our friendship no matter what changes?" },

  // Group — questions to ask when playing with three or more people
  { category: "Group", prompt: "Go around: what's one word you'd use to describe the energy of this group?" },
  { category: "Group", prompt: "Who in this group would you call first in a crisis, and why?" },
  { category: "Group", prompt: "What's something you appreciate about the person to your left?" },
  { category: "Group", prompt: "Who here has changed the most since you met them?" },
  { category: "Group", prompt: "What's a first impression you had of someone in this group that turned out to be wrong?" },
  { category: "Group", prompt: "If this group had to survive a week in the wild, who's the leader and who's the liability?" },
  { category: "Group", prompt: "Who in this room gives the best advice, and what did they once tell you?" },
  { category: "Group", prompt: "What's a memory with this group that still makes you laugh?" },
  { category: "Group", prompt: "Point to someone: what's a quality of theirs you wish you had more of?" },
  { category: "Group", prompt: "Who here would you trust with your biggest secret?" },
  { category: "Group", prompt: "What's something this group has helped you get through?" },
  { category: "Group", prompt: "If we started a business together, what would it be and who does what?" },
  { category: "Group", prompt: "Who in this group is most different from you, and what do you learn from them?" },
  { category: "Group", prompt: "What's a tradition or inside joke this group has that outsiders never get?" },
  { category: "Group", prompt: "Whose life advice would you most want to follow right now?" },
  { category: "Group", prompt: "What's something you've never told this group but feel safe saying now?" },
  { category: "Group", prompt: "Go around: what's one thing you're grateful for this week?" },
  { category: "Group", prompt: "Who here has seen you at your worst and stuck around?" },
  { category: "Group", prompt: "What do you think this group would say is your best quality?" },
  { category: "Group", prompt: "If you had to swap lives with someone in this room for a week, who and why?" },
  { category: "Group", prompt: "What's a moment someone in this group really showed up for you?" },
  { category: "Group", prompt: "Who in this group is most likely to become famous, and for what?" },
  { category: "Group", prompt: "What's something you admire about how this group treats each other?" },
  { category: "Group", prompt: "Go around: what's a small win you had recently that you didn't get to share?" },
  { category: "Group", prompt: "Who here challenges your thinking the most?" },
  { category: "Group", prompt: "What's a hard question you wish someone in this group would ask you?" },
  { category: "Group", prompt: "If this group made a time capsule tonight, what should go in it?" },
  { category: "Group", prompt: "Who in this room would you want in your corner during a tough negotiation?" },
  { category: "Group", prompt: "What's something you've learned from watching someone else in this group live their life?" },
  { category: "Group", prompt: "Go around: what's one thing you're working on about yourself right now?" },
  { category: "Group", prompt: "Who here makes you feel the most like yourself?" },
  { category: "Group", prompt: "What's a story about this group you'll still be telling in 20 years?" },
  { category: "Group", prompt: "If the group had to give one person an award tonight, who and what for?" },
  { category: "Group", prompt: "What's something you assume everyone here knows about you but might not?" },
  { category: "Group", prompt: "Who in this group would you go to for brutal honesty?" },
  { category: "Group", prompt: "What's a way this group has changed your life for the better?" },
  { category: "Group", prompt: "Go around: what's something you're looking forward to in the next month?" },
  { category: "Group", prompt: "Who here would you want to road trip across the country with, and who would you not?" },
  { category: "Group", prompt: "What's a topic this group avoids that we probably shouldn't?" },
  { category: "Group", prompt: "Who in this room has the most underrated sense of humor?" },
  { category: "Group", prompt: "What's something you'd want this group to do for you if you were struggling and hiding it?" },
  { category: "Group", prompt: "Go around: describe your current life in a movie title." },
  { category: "Group", prompt: "Who here do you wish you spent more one-on-one time with?" },
  { category: "Group", prompt: "What's a value you think everyone in this group shares?" },
  { category: "Group", prompt: "If this group had to vote, who's the most likely to give a great toast at a wedding?" },
  { category: "Group", prompt: "What's a compliment you've overheard someone give about a person in this room?" },
  { category: "Group", prompt: "Who in this group has taught you the most about loyalty?" },
  { category: "Group", prompt: "Go around: what's a question you're sitting with in your life right now?" },
  { category: "Group", prompt: "What would this group be missing if one of us hadn't joined?" },
  { category: "Group", prompt: "Who here would you trust to plan your birthday with zero input from you?" },
  { category: "Group", prompt: "What's something this group does that you hope never changes?" },
  { category: "Group", prompt: "Go around: what's one thing you need more of right now, and can anyone here help?" },
  { category: "Group", prompt: "Who in this room surprised you the most once you got to know them?" },
  { category: "Group", prompt: "What's a moment you felt proud to be part of this group?" },
  { category: "Group", prompt: "If we all had to describe the person to our right in one sentence, what would you say?" },
  { category: "Group", prompt: "What do you hope is still true about this group ten years from now?" },
  { category: "Group", prompt: "Go around: what's a belief you've changed your mind about in the last few years?" },
  { category: "Group", prompt: "Who in this group would you want to raise your kids if you couldn't, and why them?" },
  { category: "Group", prompt: "What's something you're afraid this group would judge you for, even a little?" },
  { category: "Group", prompt: "Go around: what's the loneliest you've felt this year, and did anyone here know?" },
  { category: "Group", prompt: "Who here do you think is hardest on themselves, and what would you tell them?" },
  { category: "Group", prompt: "What's a way this group holds you accountable that you're grateful for?" },
  { category: "Group", prompt: "Go around: what does 'a good life' mean to you right now?" },
  { category: "Group", prompt: "Who in this room has a strength you think they don't see in themselves?" },
  { category: "Group", prompt: "What's something you've been pretending is fine that isn't?" },
  { category: "Group", prompt: "Go around: what's a fear that's quietly shaping your decisions lately?" },
  { category: "Group", prompt: "Who here has forgiven you for something, and did you ever properly thank them?" },
  { category: "Group", prompt: "What's a conversation this group had that actually changed how you think?" },
  { category: "Group", prompt: "Go around: what's something you're proud of that nobody really congratulated you for?" },
  { category: "Group", prompt: "Who in this group would notice first if you weren't okay?" },
  { category: "Group", prompt: "What's a way you've grown that you credit at least partly to people in this room?" },
  { category: "Group", prompt: "Go around: what did you need to hear as a kid that nobody said?" },
  { category: "Group", prompt: "Who here do you owe an apology or an overdue thank-you?" },
  { category: "Group", prompt: "What's something about your life right now you'd change if you weren't afraid?" },
  { category: "Group", prompt: "Go around: what's a version of yourself you're trying to grow into?" },
  { category: "Group", prompt: "Who in this group models something you want more of in your own life?" },
  { category: "Group", prompt: "What's a truth about yourself you've only recently accepted?" },
  { category: "Group", prompt: "Go around: what are you grieving right now, even quietly?" },
  { category: "Group", prompt: "Who here helps you take yourself less seriously in a good way?" },
  { category: "Group", prompt: "What's something this group could do better at supporting each other on?" },
  { category: "Group", prompt: "Go around: what's a question you're too scared to ask someone in your life?" },
  { category: "Group", prompt: "Who in this room has seen a side of you most people never do?" },
  { category: "Group", prompt: "What's a way you've felt like an outsider in this group, even briefly?" },
  { category: "Group", prompt: "Go around: what's something you're unlearning right now?" },
  { category: "Group", prompt: "Who here would you want to give a speech at your funeral, and what would you hope they'd say?" },
  { category: "Group", prompt: "What's something you assume everyone here has figured out that you haven't?" },
  { category: "Group", prompt: "Go around: what's a hard year taught you that actually paid off?" },
  { category: "Group", prompt: "Who in this group do you compare yourself to, and is that fair to either of you?" },
  { category: "Group", prompt: "What's something you've never said out loud to this group but have felt for a long time?" },
  { category: "Group", prompt: "Go around: what do you need to forgive yourself for?" },
  { category: "Group", prompt: "Who here would tell you the truth even if it cost them the friendship?" },
  { category: "Group", prompt: "What's a way this group has shaped your values without you noticing at the time?" },
  { category: "Group", prompt: "Go around: what's something good in your life you're afraid to fully enjoy?" },
  { category: "Group", prompt: "Who in this room do you think carries the most that they don't talk about?" },
  { category: "Group", prompt: "What's a moment in this group's history you think we handled badly, and what did it teach us?" },
  { category: "Group", prompt: "Go around: what's a dream you've mostly stopped mentioning but haven't given up on?" },
  { category: "Group", prompt: "Who here has changed your mind about what friendship is supposed to look like?" },
  { category: "Group", prompt: "What's something you'd want this group to remember about you if you moved far away?" },
  { category: "Group", prompt: "Go around: when did you last feel genuinely proud of yourself?" },
  { category: "Group", prompt: "Who in this group would you want beside you on the worst day of your life?" },
  { category: "Group", prompt: "What's a way you've held back from this group that you'd like to stop doing?" },
  { category: "Group", prompt: "Go around: what's something you're still healing from?" },
  { category: "Group", prompt: "Who here do you wish understood you better, and what would you want them to know?" },
  { category: "Group", prompt: "What's a promise you'd be willing to make to this group tonight?" },
  { category: "Group", prompt: "Go around: what's one thing you hope is different about your life a year from now?" },
  { category: "Group", prompt: "If this were the last time this group was all together, what would you want to say before we left?" },
];

export function shuffledOrder(length: number): number[] {
  const order = Array.from({ length }, (_, i) => i);
  for (let i = order.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [order[i], order[j]] = [order[j], order[i]];
  }
  return order;
}
